#Copyright 2017 Reactive Ops Inc.
#
#Licensed under the Apache License, Version 2.0 (the “License”);
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an “AS IS” BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.


version: 2

jobs:
  build:
    machine: true
    environment:
      PROJECT_NAME: pentagon-integration
    working_directory: ~/pentagon
    steps:
      - checkout
      - run: 
          name: ECR Login
          command: |
            eval $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - run:
          name: Build Docker Image
          command: |
            docker pull 338430314199.dkr.ecr.ap-northeast-1.amazonaws.com/pentagon:latest || true
            docker build --cache-from 338430314199.dkr.ecr.ap-northeast-1.amazonaws.com/pentagon:latest -t pentagon:latest .
            docker tag pentagon:latest 338430314199.dkr.ecr.ap-northeast-1.amazonaws.com/pentagon:latest
            docker tag pentagon:latest 338430314199.dkr.ecr.ap-northeast-1.amazonaws.com/pentagon:${CIRCLE_SHA1}
      - run:
          name: Unit Tests
          command: |
            docker run pentagon \
              bash -c "\
                pip install -r pentagon/lib/tests/requirements.txt && \
                cd pentagon && nosetests"                
      - run:
          name: Test Start Project
          command: |
            docker run \
              -v `pwd`:/tmp \
              -e PROJECT_NAME=${PROJECT_NAME} \
              --rm pentagon \
              pentagon start-project ${PROJECT_NAME} \
              --aws-access-key=${AWS_ACCESS_KEY_ID} \
              --aws-secret-key=${AWS_SECRET_ACCESS_KEY} \
              --aws-default-region=ap-northeast-1 \
              --aws-availability-zones="ap-northeast-1a, ap-northeast-1c" \
              --dns-zone="integration.hillghost.com" \
              --workspace-directory=/tmp
      # - run:
      #     name: Test VPC
      #     command: |
      #       docker run \
      #         -v `pwd`:/tmp \
      #         bash -c "
      #           cd /tmp/
      #         "
      #       # cd ${PROJECT_NAME}
      #       # source config/local/env-vars.sh
      #       # pip install -r requirements.txt
      #       # cd config/local/
      #       # bash local-config-init
      #       ls ${PROJECT_NAME}-infrastructure
      #       ls
      - run:
          name: Push Images
          command: |
            docker push 338430314199.dkr.ecr.ap-northeast-1.amazonaws.com/pentagon:latest
            docker push 338430314199.dkr.ecr.ap-northeast-1.amazonaws.com/pentagon:${CIRCLE_SHA1}

